[package]
name = "messaging"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
documentation.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
flume.workspace = true
